//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAPDEMO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public int IDSinhVien { get; set; }
        public Nullable<int> IDLopHoc { get; set; }
        public Nullable<int> IDKhoaDaoTao { get; set; }
        public string MaSV { get; set; }
        public string HoTenSV { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string CMND { get; set; }
        public string TenKhoaDaoTao { get; set; }
        public string Email { get; set; }
        public string TenLop { get; set; }
        public string TenCN { get; set; }
    }
}
